version: "3.9"
services:
  mongo-db:
    image: mongo:6.0.6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=isra
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/data/db
